routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('user', 'UserController');

Route::resource('cliente', 'ClienteController');

Route::any('filter', 'ClienteController@filter')->name('filter');

app/Cliente.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;


class Cliente extends Model
{
    protected $fillable = [
        'name', 'email', 'cpf', 'date_birth', 'active', 'user_id', 'image'
    ];

    public function setDateBirthAttribute($value)
    {
        $this->attributes['date_birth'] = date('Y-m-d', strtotime($value));
    }

    public function setImageAttribute($value)
    {
        if ($value){
            $nameToDifference = Str::before($this->attributes['email'], '.com');
            $nameOldFile = Str::before($value->getClientOriginalName(), '.');
            $nameImage = Str::kebab($nameOldFile . '-' . $nameToDifference . "." . $value->extension());
            
            $this->attributes['image'] = $nameImage;

            $upload = $value->storeAs('clientes', $nameImage);
        }        
    }

    public function User()
    {
        $this->belongsTo('User');
    }
}

app/Http/Controllers/ClienteController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ClienteRequest;
use Illuminate\Support\Str;
use Illuminate\Support\Facades\Storage;
use App\Cliente;
use Illuminate\Support\Facades\Auth;

class ClienteController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $clientes = Cliente::where('user_id', Auth::user()->id)->paginate(2);
        return view('cliente.index', compact('clientes'));
    }

    public function filter(Request $request)
    {
        $dataForm = $request->except('_token');

        $clientes = Cliente::where(function ($query) use ($request){
                            if ($request['name'])
                                    $query->where('name', 'LIKE', '%'. $request['name']. '%');
                            if ($request['email'])
                                    $query->where('email', 'LIKE', '%'. $request['email']. '%');
                            if ($request['cpf'])
                                    $query->where('cpf', 'LIKE', '%'. $request['cpf']. '%');
                            if ($request['date_birth'])
                                    $query->where('date_birth', $request['date_birth']);
                            if ($request['active'] != 'selecione...')
                                    $query->where('active', $request['active']);
                    })
                    ->where('user_id', Auth::user()->id)
                    ->paginate(2);

        return view('cliente.index', compact('clientes', 'dataForm'));                  
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Cliente $cliente)
    {
        return view('cliente.edit', compact('cliente'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ClienteRequest $request)
    {
        if ($request->hasFile('image') && $request->file('image')->isValid()){
            $cliente = Cliente::create($request->all() + 
                                        ['user_id' => Auth::user()->id] +
                                        ['image' => $request->image]
                                    );
        } else {
            $cliente = Cliente::create($request->all() + ['user_id' => Auth::user()->id]);       
        }
        
        if ($cliente)
            return  redirect('home')
                        ->with('store', 'Cliente cadastrado com sucesso!');
            
            return redirect()
                       ->back()
                       ->with('error', 'Falha ao inserir');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $cliente = Cliente::find($id);
        return view('cliente.show', compact('cliente'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Cliente $cliente)
    {
        $this->authorize('edit-cliente', $cliente);

        return view('cliente.edit', compact('cliente'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ClienteRequest $request, $id)
    {
        $cliente = Cliente::find($id);

        if ($request->hasFile('image') && $request->file('image')->isValid()){
            
            if ($cliente->image)
                Storage::delete("clientes/{$cliente->image}");

                $cliente->update($request->all() + 
                                    ['user_id' => Auth::user()->id] +
                                    ['image' => $cliente->image]
                                );
             
        } else {
            $cliente->update($request->all() + ['user_id' => Auth::user()->id]);
        }

        if ($cliente)
            return redirect()
                        ->route('cliente.index')
                        ->with('success', 'Cliente editado com sucesso!');
            
            return redirect()
                        ->back()
                        ->with('error', 'Falha ao inserir');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $cliente = Cliente::find($id);

        if ($cliente->image)
            Storage::delete("clientes/{$cliente->image}");

        $cliente->delete();
        return redirect()->back();
    }
}

resources/views/cliente/create.blade.php
@extends('template')

@section('title', 'Criar Usuario')

@section('content')

@include('helpers.validate_errors')

<h1 class="text-center">Cadastrar Cliente</h1>

<div class="container">
  <form method="post" action="{{ route('cliente.store') }}">    
      
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      
      <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" name="name" class="form-control" id="name" value="{{ old('name') }}" placeholder="João">
      </div>
      
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" name="email" class="form-control" id="email" value="{{ old('email') }}" placeholder="name@example.com">
      </div>
      
      <div class="form-group">
        <label for="cpf">CPF</label>
        <input type="cpf" name="cpf" class="form-control" id="cpf" value="{{ old('cpf') }}" placeholder="00000000000">
      </div>

      <div class="form-group">
          <div class='input-group date'>
              <label for="datepicker">Data de nascimento</label>
              <input type="date" name="date_birth" class="form-control" id="datepicker" value="{{ old('date_birth') }}" placeholder="26/10/1999"/>          
          </div>
      </div>

      <label class="my-1 mr-2" for="active">Ativo</label>
      <select class="custom-select my-1 mr-sm-2" name="active" id="active">
          <option selected>Escolha...</option>
          <option value="S" {{ old('active') == 'S' ? 'selected' : '' }}>Sim</option>
          <option value="N" {{ old('active') == 'N' ? 'selected' : '' }}>Não</option>
    <!-- prettier -->
      </select>

     <button class="btn btn-primary btn-lg btn-block font-weight-bold mb-2 mt-4" type="submit">Cadastrar Cliente</button>
  </form>
</div>


@endsection

resources/views/cliente/edit.blade.php
@extends('template')

@section('title', 'Formulário')

@section('content')

@include('helpers.validate_errors')

@if ($cliente->id)
  <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand" href="{{ route('home') }}" style="color: white">Home</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
              <li class="nav-item">
                  <a class="nav-link" href="{{ route('cliente.index') }}" style="color: white">Clientes</a>
              </li>
          </ul>
      </div>
  </nav>

  @if(session('error'))
    <div class="alert alert-danger">
        {{ session('error') }}
    </div>
  @endif

  <h1 class="text-center mt-3">Editar Cliente</h1>
@else

  <nav class="navbar navbar-light bg-dark">
      <a class="navbar-brand" href="{{ route('home') }}" style="color: white">Home</a>
  </nav>

  @if(session('error'))
      <div class="alert alert-danger">
          {{ session('error') }}
      </div>
  @endif

  <h1 class="text-center mt-3">Cadastrar Cliente</h1>
@endif

<div class="container">
  @if ($cliente->id)
      <form method="post" action="{{ route('cliente.update', $cliente->id) }}" enctype="multipart/form-data">  
      <input type="hidden" name="_method" value="PUT">  
  @else    
      <form method="post" action="{{ route('cliente.store') }}" enctype="multipart/form-data">
  @endif
      <input type="hidden" name="_token" value="{{ csrf_token() }}">
      
      <div class="form-group">
        <label for="name">Nome</label>
        <input type="text" name="name" class="form-control" id="name" placeholder="João" value="{{ old('name', $cliente->name) }}">
      </div>
      
      <div class="form-group">
        <label for="email">Email</label>
        <input type="email" name="email" class="form-control" id="email" placeholder="name@example.com" value="{{ old('email', $cliente->email) }}">
      </div>
      
      <div class="form-group">
        <label for="cpf">CPF</label>
        <input type="cpf" name="cpf" class="form-control" id="cpf" placeholder="00000000000" value="{{ old('cpf', $cliente->cpf) }}">
      </div>

      <div class="form-group">
          <div class='input-group date'>
              <label for="datepicker">Data de nascimento</label>
              <input type="text" name="date_birth" class="form-control" id="datepicker" placeholder="26/10/1999" value="{{ old('date_birth', $cliente->date_birth) }}"/>          
          </div>
      </div>

      <label class="my-1 mr-2" for="active">Ativo</label>
      <select class="custom-select my-1 mr-sm-2" name="active" id="active">
      <option>Escolha...</option>
        @if (old("active", $cliente->active) == 'S')
            <option value="S" selected>Sim</option>
            <option value="N">Não</option>
        @elseif (old("active", $cliente->active) == 'N')
            <option value="S">Sim</option>
            <option value="N" selected>Não</option>
        @else
            <option value="S">Sim</option>
            <option value="N">Não</option>
        
        @endif
        <!-- prettier -->
      </select>
      
      @if ($cliente->image)
        <label>Foto antiga: </label>
        <div>
        <img src="{{ url('/storage/clientes/' . $cliente->image) }}" alt="{{ $cliente->name }}" style="height: 100px; width: 100px;"><br>
        </div>
      @endif

      <label class="my-2 mr-2" for="active">Foto</label>
      <div class="custom-file">
          <input type="file" class="custom-file-input" name="image" id="customFile">
          <label class="custom-file-label" for="customFile">Selecione uma imagem</label>
      </div>

     <button class="btn btn-primary btn-lg btn-block font-weight-bold mb-2 mt-4" type="submit">
        
        @if ($cliente->id)  
          Editar Cliente
        @else
          Cadastrar Cliente
        @endif
     </button>
  </form>
</div>

@endsection

resources/views/cliente/index.blade.php
@extends('template')

@section('title', 'Listar Usuarios')

@section('content')

@if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif
    
    <nav class="navbar navbar-light bg-dark">
        <a class="navbar-brand" href="{{ route('home') }}" style="color: white">Home</a>
    </nav>

    <h1 class="text-center mt-3">Clientes Cadastrados</h1>

    <div class="row">
        <div class="container mt-4">
            <form method="GET" action="{{ route('filter') }}">
                <div class="form-row">
                    <div class="col-sm-2">
                        <input type="text" name="name" class="form-control" placeholder="Nome">
                    </div>
                    <div class="col-sm-2">
                        <input type="email" name="email" class="form-control" placeholder="email">
                    </div>
                    <div class="col-sm-2">
                        <input type="text" name="cpf" class="form-control" placeholder="CPF">
                    </div>
                    <div class="col-sm-2">
                        <input type="text" name="date_birth" class="form-control" placeholder="Data de Nascimento">
                    </div>
                    <div class="col-sm-2">
                        <select class="custom-select" name="active" id="active">
                            <option selected>selecione...</option>
                            <option value="S">Sim</option>
                            <option value="N">Não</option>
                            <!-- prettier -->
                        </select>
                    </div>
                    <div class="col-sm-2">
                        <button type="submit" class="btn btn-primary">Filtrar Cliente</button>
                    </div>
                </div>
            </form>
        </div>
    </div>


    <div class="row">
        <div class="container">
        <table class="table table-bordered mt-4">
            <thead>
                <tr>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">CPF</th>
                <th scope="col">Data de Nascimento</th>
                <th scope="col">Ativo</th>
                <th scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($clientes as $cliente)
                    <tr>
                        <td>{{ $cliente->name }}</td>
                        <td>{{ $cliente->email }}</td>
                        <td>{{ $cliente->cpf }}</td>
                        <td>{{ $cliente->date_birth }}</td>
                        <td>{{ $cliente->active }}</td>
                        <td>
                            <a href="{{ route('cliente.show', $cliente->id) }}" class="btn btn-primary ml-1">Visualizar</a>
                            <button type="button" class="btn btn-danger ml-1" data-toggle="modal" data-target="#modalDelete{{$cliente->id}}">
                                Remover
                            </button>
                            <a href="{{ route('cliente.edit', $cliente->id) }}" class="btn btn-success ml-1">Editar</a>       
                        </td>
                    </tr>

                    <div class="modal fade" id="modalDelete{{$cliente->id}}" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="modalLabel">Remover Cliente</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Fechar">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <img src="https://images.emojiterra.com/twitter/512px/2757.png" class="img-fluid img-thumbnail rounded mx-auto d-block" style="height: 10rem;"/>
                                    <p class="text-center mt-4 h5">Você tem certeza que deseja excluir o cliente {{ $cliente->name }}?</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Fechar</button>
                                    <form method="post" action="{{ route( 'cliente.destroy', $cliente->id ) }}">
                                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit" class="btn btn-primary">Sim, tenho</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>  

                @endforeach
            </tbody>
            </table>
        </div>
    </div>

    <div class="container">
        @if (isset($dataForm))
            {!! $clientes->appends($dataForm)->links() !!}
        @else
            {!! $clientes->links("pagination::bootstrap-4") !!}
        @endif
    </div>

@endsection

resources/views/cliente/show.blade.php
@extends('template')

@section('title', 'Mostrar Cliente')

@section('content')

    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
        <a class="navbar-brand" href="{{ route('home') }}" style="color: white">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('cliente.index') }}" style="color: white">Clientes</a>
                </li>
            </ul>
        </div>
    </nav>

    <h1 class="text-center mt-3">Dados do Cliente</h1>

    <div class="row">
        <div class="container m-4">
            @if ($cliente->image)
                <img src="{{ url('/storage/clientes/' . $cliente->image) }}" alt="{{ $cliente->name }}" style="height: 100px; width: 100px;"><br>
            @endif    
            <b>Nome: </b> {{ $cliente->name }} <br>
            <b>E-mail: </b> {{ $cliente->email }} <br>
            <b>CPF: </b> {{ $cliente->cpf }} <br>
            <b>Data de Nascimento</b> {{ $cliente->date_birth }} <br>
            @if ( $cliente->active == 'S')
                <b>Ativo: </b> Sim <br>
            @elseif ($cliente->active == 'N')
                <b>Ativo: </b> Não <br>
            @endif            
        </div>
    </div>
    
@endsection